# main text of home
name: Michael Reeve
bio: Engineer, Mountaineer, Photographer

# twitter summary info
description: A blog about my adventures and ponderings

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://www.electricentity.com
permalink: /:title/

github: electricentity

authors:
    michaelreeve:
        name: Michael Reeve
        bio: Engineer, Mountaineer, Photographer
        external-image: false
        picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

blog: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["Rakefile", "README.md", "Gemfile", "Gemfile.lock", "CLAUDE.md", "bin"]
